### ISSUE TITLE
Name for setting file is wrong.

### ISSUE THREAD

**Issue by gigony** [tillt/RTagsComplete#10]
First, thanks for upgrading the original RTagsComplete :+1: 

It seems that 
https://github.com/tillt/RTagsComplete/blob/92f24bfacde75b722480e13b1c0f26296292ad1b/plugin/settings.py#L13
'RtagsComplete.sublime-settings' file's name needs to be 'RTagsComplete.sublime-settings'.
Without it, it cannot read User's settings correctly (because User's setting file name would be RTagsComplete.sublime-settings).

Thanks.

**Comment by tillt** [comment]
Fixed by https://github.com/tillt/RTagsComplete/commit/e919c1a43125ac18c2928ca3dc48a411e981d1bc
