### ISSUE TITLE
Possible issue with symbol info

### ISSUE THREAD

**Issue by Wintaru** [tillt/RTagsComplete#12]
I'm not sure if this is a problem with this plugin or my version of rtags, but my rc command has no idea what the --json argument is for. If I run rc --absolute-path --symbol-info 'pathtofile' from the shell it works fine, but I took the --json argument out of my key bindings and it looks like the plugin is expecting the information to be returned in json format, so perhaps my version of rtags is old? I couldn't find any documentation on rtags about this flag.

**Comment by tillt** [comment]
Seems to me that RTags added the `--json` flag around 2.5 for `--symbol-info`.

See https://github.com/Andersbakken/rtags/commit/85d56fd6f192b2d75e35e118761f88e1b7b6b4c6

Can you please confirm your exact `rc` version?

**Comment by tillt** [comment]
@Wintaru  ^^

**Comment by Wintaru** [comment]
Yeah our version is 2.0.82. Apparently the latest version of rtags doesn't build on Debian Wheezy, but for reasons we don't understand. We get this error even though we're using Clang 3.5:

Compiler with complete C++11 support required ( >= GCC 4.9 or >= Clang 3.3)

I made changes to the source for your plugin that removes the OnHover function so I don't get that pop up "Rtags returned with error 1" and I will have to be ok with not having symbol info for now.

**Comment by tillt** [comment]
I would actually like to re-open this -- as a reminder for me to add to the documentation that we need at least RTags 2.5 for now.

We could also consider making the use of the `--json` flag optional and keep the old way of parsing symbol into around as well. That however is a larger thing, nothing I would jump at right now.

**Comment by Wintaru** [comment]
Sure no problem, I figured you had bigger fish to fry. I'm looking into if we can at least build rtags 2.5, as that would be enough to get this working.

**Comment by tillt** [comment]
@Wintaru the following commit might then make your life a little easier; it adds a `hover` flag to disable that on-hover-show-symbol-info feature.
https://github.com/tillt/RTagsComplete/commit/92554f1ccca9455f4bf86e36572b7487d380cca9

**Comment by Wintaru** [comment]
Thanks @tillt !

**Comment by tillt** [comment]
Fixed by https://github.com/tillt/RTagsComplete/commit/92554f1ccca9455f4bf86e36572b7487d380cca9
