### ISSUE TITLE
global name 'vc_manager' is not defined.

### ISSUE THREAD

**Issue by Wintaru** [tillt/RTagsComplete#15]
Getting this now when trying to go to symbol:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1066, in run_
    return self.run(edit, **args)
  File "/home/<user>/.config/sublime-text-3/Installed Packages/RTagsComplete.sublime-package/rtags.py", line 154, in run
NameError: global name 'vc_manager' is not defined

**Comment by tillt** [comment]
Can you check if staging fixes it for you?

I believe you ran into https://github.com/tillt/RTagsComplete/issues/14 - hopefully that is gone by now.

**Comment by Wintaru** [comment]
Yep staging works, thanks!

**Comment by hessryanm** [comment]
Hey, I'm running into this error too.  I'm not sure what you mean by "staging" to fix it.

**Comment by Wintaru** [comment]
> Hey, I'm running into this error too. I'm not sure what you mean by "staging" to fix it.

You have to manually install the package by cloning the git repo in your Packages directory, the run
`git checkout staging`

You can't use package manager in order to do this so if you have it installed with that you would need to remove it first.

FWIW this isn't working for me still, even using the staging branch.

**Comment by hessryanm** [comment]
I have the git repo checked out in the Sublime Text 3/Installed Packages directory, but it doesn't appear to recognize it as a package.  Are there more clear instructions on how to install manually?

**Comment by Wintaru** [comment]
It needs to be in Sublime Text 3/Packages

**Comment by hessryanm** [comment]
Thanks!  That helped me figure it out, and staging made it work for me
again.  Good luck!
