### ISSUE TITLE
rtags_go_backwards not working

### ISSUE THREAD

**Issue by Wintaru** [tillt/RTagsComplete#16]
When I use rtags to go to a symbol, and then try rtags_go_backwards it doesn't go back to the previous line, it seems to jump all over the place, I don't get a consistent place when I try rtags_go_backwards

**Comment by tillt** [comment]
Looking into that over the weekend.

**Comment by tillt** [comment]
So far I have not been able to reproduce this problem. Maybe you got an idea for quickly hitting this bug @Wintaru ?
Please make sure you are using "staging" as that always is the latest prerelease available.

**Comment by Wintaru** [comment]
It happens pretty much constantly for me, I turned verbose logging on (also made sure I have the current from staging). When I try to go to a function, this turned up in the console:

    Traceback (most recent call last):
      File "/opt/sublime_text/sublime_plugin.py", line 462, in run_callback
    expr()
      File "/opt/sublime_text/sublime_plugin.py", line 603, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
      File "/home/<user>/.config/sublime-text-3/Packages/RTagsComplete/rtags.py", line 726, in on_activated
        if not supported_view(view):
      File "/home/<user>/.config/sublime-text-3/Packages/RTagsComplete/rtags.py", line 65, in supported_view
        scope = view.scope_name(selection[0].a)
      File "/opt/sublime_text/sublime.py", line 649, in __getitem__
    raise IndexError()
    IndexError

But nothing in the console when I try to go backwards.

**Comment by tillt** [comment]
@Wintaru very interesting - so the problem seems to be triggered already when a view gains focus. I have added some more checks to the `supported_view` function, hoping to get more information out of that. Could you please pull in the latest "staging", make sure logging is verbose and retry?

**Comment by Wintaru** [comment]
This is me clicking on a function in a c file, then hitting F2.

RTags:DEBUG: 2018-08-15 12:06:58,447 rtags.py::on_activated [MainThread]: Activated supported view for view-id 21
RTags:DEBUG: 2018-08-15 12:06:58,448 vc.py::deactivated [MainThread]: Deactivating view-id 20
RTags:DEBUG: 2018-08-15 12:06:58,448 idle.py::deactivated [MainThread]: Deactivated
RTags:DEBUG: 2018-08-15 12:06:58,448 fixits.py::deactivated [MainThread]: Deactivated
RTags:DEBUG: 2018-08-15 12:06:58,449 vc.py::activated [MainThread]: Activating view-id 21
RTags:DEBUG: 2018-08-15 12:06:58,449 idle.py::activated [MainThread]: Activated
RTags:DEBUG: 2018-08-15 12:06:58,449 fixits.py::activated [MainThread]: Activated
RTags:DEBUG: 2018-08-15 12:07:02,416 jobs.py::run_async [MainThread]: Starting async job RTBaseCommand24
RTags:DEBUG: 2018-08-15 12:07:02,416 indicator.py::start [MainThread]: Indicator now running for 1 processes
RTags:DEBUG: 2018-08-15 12:07:02,417 indicator.py::start [MainThread]: Starting indicator
RTags:DEBUG: 2018-08-15 12:07:02,421 jobs.py::run_process [Thread-5658]: Starting process job ['/usr/bin/rc', '--absolute-path', '-f', 'filepathhere.c:2681:16']
RTags:DEBUG: 2018-08-15 12:07:02,427 jobs.py::run_process [Thread-5658]: Process running with timeout None, input-length 0
RTags:DEBUG: 2018-08-15 12:07:02,428 jobs.py::run_process [Thread-5658]: Communicating with process via <bound method RTagsJob.communicate of <RTagsComplete.plugin.jobs.RTagsJob object at 0x7fc292eea450>>
RTags:DEBUG: 2018-08-15 12:07:02,428 jobs.py::communicate [Thread-5658]: Static communicate with timeout None for <bound method RTagsJob.communicate of <RTagsComplete.plugin.jobs.RTagsJob object at 0x7fc292eea450>>
RTags:DEBUG: 2018-08-15 12:07:09,407 jobs.py::communicate [Thread-5658]: Static communicate terminating
RTags:DEBUG: 2018-08-15 12:07:09,407 jobs.py::run_process [Thread-5658]: Output-length: 126
RTags:DEBUG: 2018-08-15 12:07:09,408 jobs.py::run_process [Thread-5658]: Process job ran for 6.99 seconds
RTags:DEBUG: 2018-08-15 12:07:09,408 rtags.py::command_done [Thread-5658]: Command done callback hit <Future at 0x7fc28fd71c10 state=finished returned tuple>
RTags:DEBUG: 2018-08-15 12:07:09,408 status.py::update_status [Thread-5658]: Signalling status with error=None
RTags:DEBUG: 2018-08-15 12:07:09,408 status.py::clear_status [Thread-5658]: Clearing status from view-id 21
RTags:DEBUG: 2018-08-15 12:07:09,409 rtags.py::command_done [Thread-5658]: Finished Command job RTBaseCommand24
RTags:DEBUG: 2018-08-15 12:07:09,460 jobs.py::done [Thread-5658]: Job RTBaseCommand24 done
RTags:DEBUG: 2018-08-15 12:07:09,460 indicator.py::stop [Thread-5658]: Stopping one indication
RTags:DEBUG: 2018-08-15 12:07:09,461 indicator.py::stop [Thread-5658]: Indicator still running for 1 processes
RTags:DEBUG: 2018-08-15 12:07:09,461 jobs.py::done [Thread-5658]: Removed bookkeeping for job RTBaseCommand24
RTags:DEBUG: 2018-08-15 12:07:09,475 indicator.py::run [Dummy-6]: Indicator stopped

**Comment by tillt** [comment]
@Wintaru hmmm - that looks all fine and dandy. 

Can you please add the complete log of:
"Jump to definition of function" (F2) and then "Return from that definition" (ctrl+shift+b)

**Comment by Wintaru** [comment]
Did you update something to generate output for Return from definition? I get no output from that. I can pull again if needed.

We started a tight sprint this week so I will try to provide feedback quickly but it may be slower than usual due to work load.

**Comment by Wintaru** [comment]
Ok interesting, it works all of a sudden. I'm not sure what changed but I did have to restart rtags and rebuild my rtags project from scratch, perhaps that was the secret sauce.

**Comment by tillt** [comment]
It may very well be that I did fix a problem here without really noticing -- so don't blame yourself or your RTags setup too much :) .... really glad it works as expected for you now.

**Comment by Wintaru** [comment]
FYI this is still broken. It works for a while and then something happens and it quits, I haven't figured out what yet.

**Comment by tillt** [comment]
@Wintaru I have identified some quirky things that may or may not have contributed to your experience here -- reopened this issue to make sure we finally get this fixed.
Please check v0.7.2 for the problem and take your time to be *sure* we don't see that quirk anymore :). Thanks a bunch for reporting the problem in the first place.

**Comment by Wintaru** [comment]
@tillt I've verified I have 0.7.2 and restarted ST. I will do some testing this morning and see but before the restart I was still seeing the issue. Will update when I know more.

**Comment by tillt** [comment]
@Wintaru I may have gotten it right this time. Please check v0.8.0.

Also note that we now got a navigation history popup that should also help in squashing any remaining irritations on that quirky bug - if they are still there.

**Comment by Wintaru** [comment]
It does seem to be working now trying with my HTR above, I will keep using it and let you know if it rears it's head again, yay!

**Comment by Wintaru** [comment]
@tillt Sure seems like this is fixed now, I haven't noticed any wrong behavior. Thanks!

**Comment by tillt** [comment]
Awesome, glad this bugger finally got sorted out.
