### ISSUE TITLE
Disabling fixits doesn't actually disable fixits

### ISSUE THREAD

**Issue by Wintaru** [tillt/RTagsComplete#40]
I have the 'fixits' setting set to false in my user config for RTagsComplete and I still get fixits all over.

**Comment by tillt** [comment]
That is a funny one - cause I fell for it just like you :D - just like you, I did not update my configuration - wonder if the update/installer could do that -- will look into that.

So, the setting got renamed a while ago - it is now called `validation`.

This should be enough;
```
  "validation": false,
```

For a more fine-grained control, the follwing can get used when `validation` is set to `True`.

```
  "validation_display_types": ["error", "warning", "fixit", "note"],
```
Say you don't care for "warnings" right now; remove them from that array while keeping. Not tested, but should work.

Please note that you will need to restart Sublime for changes on that setting to become effective.

**Comment by Wintaru** [comment]
Thanks!
